gjk4all_p2000.settings:
  type: config_object
  label: 'GJK4All P2000 settings'
  mapping:
    gjk4all_p2000:
      type: mapping
      mapping:
        page_title:
          type: text
          label: 'P2000 block title:'
        capcodes:
          type: text
          label: 'P2000 monitored capcodes:'
        max_age:
          type: integer
          label: 'Message age shown:'
        date_type:
          type: date_format
          label: 'Date format:'
          translatable: true
          translation context: 'PHP date format'
block.gjk4all_p2000_block_settings:
  type: block_settings
  label: 'GJK4All P2000 block'
  mapping:
    gjk4all_p2000_block_settings:
      type: text
      label: 'GJK4All P2000 block settings'

